version: "3"

services:
  
  mysql:
    build: ./database
    container_name: mysql
    restart: always
    ports:
      - 3306
  
  django:
    build: .
    restart: always
    ports:
      - 8000
    depends_on:
      - mysql
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - django