version: "3"

services:
  
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: gujarat
    volumes:
      - ./database/gujarat_database.sql:/docker-entrypoint-initdb.d/gujarat.sql
    ports:
      - 3306:3306
  
  django:
    build: .
    container_name: django
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - mysql
  
  nginx:
    image: nginx:stable-alpine-slim
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django