version: "2"
services:
  
  mysql:
    image: yobasystems/alpine-mariadb:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: gujarat
    volumes:
      - ./database/gujarat_database.sql:/docker-entrypoint-initdb.d/gujarat.sql
    ports:
      - 3306
  
  django:
    image: babodesi/gujarat
    restart: always
    command: python3 manage.py runserver 0.0.0.0:80
    ports:
      - 80:80
    depends_on:
      - mysql