version: "2"
services:
  
  mysql:
    image: babodesi/gujaratdb
    container_name: mysql
    restart: always
    ports:
      - 3306
  
  django:
    image: babodesi/gujarat
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000
    depends_on:
      - mysql

  nginx:
    image: babodesi/gujaratnginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - django